FROM andreptb/tomcat:6.0.48-jdk6

ENV JAVA_VERSION=6 JAVA_UPDATE=45 JAVA_BUILD=06 JAVA_HOME=/usr/lib/jvm/default-jvm GROOVY_VERSION=2.3.11 LANG=C.UTF-8 GLIBC_VERSION=2.23-r3

ENV CATALINA_HOME=/usr/local/tomcat PATH=/usr/local/tomcat/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin TOMCAT_MAJOR_VERSION=6 TOMCAT_MINOR_VERSION=6.0.48 APACHE_MIRROR=https://archive.apache.org/dist APR_VERSION=1.5.2 TOMCAT_NATIVE_VERSION=1.2.8

CMD ["catalina.sh","run"]